### ISSUE TITLE
What does each ball represent?

### ISSUE THREAD

**Issue by riklopfer** [mjskay/election-galton-board#4]
This is not clear to me. Is each ball a single vote in the electoral college? Or is each ball a state which carry different values?

**Comment by mjskay** [comment]
Each ball is one possible outcome of the election, according to the uncertainty in the underlying models. One ball is a 1/50 chance the election turns out where that ball lands.

**Comment by mjskay** [comment]
See also the new explanation under ["how does this work?"](https://presidential-plinko.com/#how-does-this-work)
